import 'package:flutter/widgets.dart';

import 'language_store.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _data = {
    'en': {
      'profile': 'Profile',
      'edit_profile': 'Edit Profile',
      'payment_option': 'Payment Option',
      'notifications': 'Notifications',
      'saved_courses': 'Saved Courses',
      'security': 'Security',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'terms_conditions': 'Terms & Conditions',
      'help_center': 'Help Center',
      'invite_friends': 'Invite Friends',
      'switch_account': 'Switch Account',
      'sign_out': 'Sign Out',
      'signing_out': 'Signing Out...',
      'student': 'Student',
      'not_set': 'Not set',
      'saving': 'Saving...',
      'update': 'Update',
      'updating': 'Updating...',
      'full_name': 'Full Name',
      'nick_name': 'Nick Name',
      'date_of_birth': 'Date of Birth',
      'email': 'Email',
      'gender': 'Gender',
      'profile_updated': 'Profile updated.',
      'profile_save_failed': 'Could not save profile. Try again.',
      'sign_in_to_update_profile': 'Please sign in to update your profile.',
      'camera_open_failed': 'Could not open camera. Please try again.',
      'gallery_open_failed': 'Could not open gallery. Please try again.',
      'notification_title': 'Notification',
      'special_offers': 'Special Offers',
      'sound': 'Sound',
      'vibrate': 'Vibrate',
      'general_notification': 'General Notification',
      'promo_discount': 'Promo & Discount',
      'payment_options': 'Payment Options',
      'app_update': 'App Update',
      'new_service_available': 'New Service Available',
      'new_tips_available': 'New Tips Available',
      'remember_me': 'Remember Me',
      'biometric_id': 'Biometric ID',
      'face_id': 'Face ID',
      'google_authenticator': 'Google Authenticator',
      'change_pin': 'Change PIN',
      'change_password': 'Change Password',
      'change_pin_soon': 'Change PIN is coming soon.',
      'google_authenticator_soon': 'Google Authenticator is coming soon.',
      'language_subcategories': 'SubCategories:',
      'language_all': 'All Language',
      'payment_option_title': 'Payment Option',
      'connected': 'Connected',
      'add_new_card': 'Add New Card',
      'card_name': 'Card Name*',
      'card_number': 'Card Number*',
      'expiry_date': 'Expiry Date*',
      'cvv': 'CVV*',
      'card_added': 'Card added.',
      'card_details_required': 'Please enter card details.',
      'terms_title': 'Terms & Conditions',
      'condition_attending': 'Condition & Attending',
      'terms_use': 'Terms & Use',
      'invite_title': 'Invite Friends',
      'invite': 'Invite',
      'invited': 'Invited',
      'share_invite': 'Share Invite Via',
      'contacts_permission_required':
          'Contacts permission is required to show your phone contacts.',
      'retry': 'Retry',
      'open_settings': 'Open settings',
      'contacts_load_failed': 'Could not load contacts.',
      'no_phone_contacts': 'No phone contacts found.',
      'invalid_contact_phone': 'This contact has no valid phone number.',
      'sms_open_failed': 'Could not open SMS app.',
      'facebook_share_open_failed': 'Could not open Facebook share.',
      'twitter_share_open_failed': 'Could not open Twitter share.',
      'gmail_share_open_failed': 'Could not open Gmail share.',
      'whatsapp_invite_title': 'Invite via WhatsApp',
      'whatsapp_send_chat': 'Send to a person in chat',
      'whatsapp_post_status': 'Post invite to WhatsApp Status',
      'whatsapp_status_hint':
          'WhatsApp opened. Select My Status inside WhatsApp to post the invite.',
      'whatsapp_share_open_failed': 'Could not open WhatsApp share.',
      'instagram_invite_title': 'Invite via Instagram',
      'instagram_send_dm': 'Send to a person in DM',
      'instagram_post_story': 'Post invite to Instagram Story',
      'instagram_dm_hint':
          'Instagram opened. Paste the invite link in a DM and send it.',
      'instagram_story_hint':
          'Instagram opened. Create a Story and add the invite link.',
      'instagram_share_open_failed': 'Could not open Instagram.',
      'linkedin_invite_title': 'Invite via LinkedIn',
      'linkedin_send_message': 'Send to a person in message',
      'linkedin_post_feed': 'Post invite on LinkedIn feed',
      'linkedin_message_hint':
          'LinkedIn opened. Paste the invite link in a message and send it.',
      'linkedin_share_open_failed': 'Could not open LinkedIn share.',
    },
    'ar': {
      'profile': 'الملف الشخصي',
      'edit_profile': 'تعديل الملف الشخصي',
      'payment_option': 'خيارات الدفع',
      'notifications': 'الإشعارات',
      'saved_courses': 'الدورات المحفوظة',
      'security': 'الأمان',
      'language': 'اللغة',
      'dark_mode': 'الوضع الداكن',
      'terms_conditions': 'الشروط والأحكام',
      'help_center': 'مركز المساعدة',
      'invite_friends': 'دعوة الأصدقاء',
      'switch_account': 'تبديل الحساب',
      'sign_out': 'تسجيل الخروج',
      'signing_out': 'جاري تسجيل الخروج...',
      'student': 'طالب',
      'not_set': 'غير محدد',
      'saving': 'جارٍ الحفظ...',
      'update': 'تحديث',
      'updating': 'جارٍ التحديث...',
      'full_name': 'الاسم الكامل',
      'nick_name': 'الاسم المختصر',
      'date_of_birth': 'تاريخ الميلاد',
      'email': 'البريد الإلكتروني',
      'gender': 'النوع',
      'profile_updated': 'تم تحديث الملف.',
      'profile_save_failed': 'تعذر حفظ الملف. حاول مرة أخرى.',
      'sign_in_to_update_profile': 'يرجى تسجيل الدخول لتحديث ملفك.',
      'camera_open_failed': 'تعذر فتح الكاميرا. حاول مرة أخرى.',
      'gallery_open_failed': 'تعذر فتح المعرض. حاول مرة أخرى.',
      'notification_title': 'الإشعارات',
      'special_offers': 'عروض خاصة',
      'sound': 'الصوت',
      'vibrate': 'اهتزاز',
      'general_notification': 'إشعارات عامة',
      'promo_discount': 'عروض وخصومات',
      'payment_options': 'خيارات الدفع',
      'app_update': 'تحديثات التطبيق',
      'new_service_available': 'خدمة جديدة متاحة',
      'new_tips_available': 'نصائح جديدة متاحة',
      'remember_me': 'تذكرني',
      'biometric_id': 'البصمة',
      'face_id': 'بصمة الوجه',
      'google_authenticator': 'مصدّق Google',
      'change_pin': 'تغيير الرقم السري',
      'change_password': 'تغيير كلمة المرور',
      'change_pin_soon': 'تغيير الرقم السري قريبًا.',
      'google_authenticator_soon': 'مصدّق Google قريبًا.',
      'language_subcategories': 'تصنيفات فرعية:',
      'language_all': 'كل اللغات',
      'payment_option_title': 'خيارات الدفع',
      'connected': 'متصل',
      'add_new_card': 'إضافة بطاقة جديدة',
      'card_name': 'اسم البطاقة*',
      'card_number': 'رقم البطاقة*',
      'expiry_date': 'تاريخ الانتهاء*',
      'cvv': 'CVV*',
      'card_added': 'تمت إضافة البطاقة.',
      'card_details_required': 'يرجى إدخال بيانات البطاقة.',
      'terms_title': 'الشروط والأحكام',
      'condition_attending': 'الشروط والحضور',
      'terms_use': 'الشروط والاستخدام',
      'invite_title': 'دعوة الأصدقاء',
      'invite': 'دعوة',
      'invited': 'تمت الدعوة',
      'share_invite': 'شارك الدعوة عبر',
      'contacts_permission_required':
          'مطلوب إذن جهات الاتصال لعرض جهات الاتصال على هاتفك.',
      'retry': 'إعادة المحاولة',
      'open_settings': 'فتح الإعدادات',
      'contacts_load_failed': 'تعذر تحميل جهات الاتصال.',
      'no_phone_contacts': 'لا توجد جهات اتصال تحتوي على رقم هاتف.',
      'invalid_contact_phone': 'جهة الاتصال لا تحتوي على رقم هاتف صالح.',
      'sms_open_failed': 'تعذر فتح تطبيق الرسائل.',
      'facebook_share_open_failed': 'تعذر فتح مشاركة فيسبوك.',
      'twitter_share_open_failed': 'تعذر فتح مشاركة تويتر.',
      'gmail_share_open_failed': 'تعذر فتح مشاركة Gmail.',
      'whatsapp_invite_title': 'دعوة عبر واتساب',
      'whatsapp_send_chat': 'إرسال لشخص في الشات',
      'whatsapp_post_status': 'نشر الدعوة على حالة واتساب',
      'whatsapp_status_hint':
          'تم فتح واتساب. اختر حالتي داخل واتساب لنشر رابط الدعوة.',
      'whatsapp_share_open_failed': 'تعذر فتح مشاركة واتساب.',
      'instagram_invite_title': 'دعوة عبر إنستجرام',
      'instagram_send_dm': 'إرسال لشخص عبر الرسائل',
      'instagram_post_story': 'نشر الدعوة على ستوري إنستجرام',
      'instagram_dm_hint':
          'تم فتح إنستجرام. الصق رابط الدعوة في رسالة خاصة ثم أرسلها.',
      'instagram_story_hint': 'تم فتح إنستجرام. أنشئ ستوري وأضف رابط الدعوة.',
      'instagram_share_open_failed': 'تعذر فتح إنستجرام.',
      'linkedin_invite_title': 'دعوة عبر لينكدإن',
      'linkedin_send_message': 'إرسال لشخص عبر الرسائل',
      'linkedin_post_feed': 'نشر الدعوة على لينكدإن',
      'linkedin_message_hint':
          'تم فتح لينكدإن. الصق رابط الدعوة في رسالة ثم أرسلها.',
      'linkedin_share_open_failed': 'تعذر فتح مشاركة لينكدإن.',
    },
  };

  static String of(BuildContext context, String key) {
    final String code = LanguageStore.current.value.code;
    final String lang = code == 'ar' ? 'ar' : 'en';
    return _data[lang]?[key] ?? _data['en']?[key] ?? key;
  }
}

extension AppStringsX on BuildContext {
  String tr(String key) => AppStrings.of(this, key);
}
